# Generated by Django 2.2.24 on 2022-06-20 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('job', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentId', models.AutoField(primary_key=True, serialize=False)),
                ('payment', models.IntegerField()),
                ('is_fullpayment', models.BooleanField(default=False)),
                ('chatId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ci', to='chat.Chat')),
                ('employerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ei', to='account.Employer')),
                ('freelancerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fi', to='account.Jobseeker')),
                ('jobId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ji', to='job.Jobs')),
            ],
        ),
    ]
