# Generated by Django 2.2.24 on 2022-06-20 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('testimonialId', models.AutoField(primary_key=True, serialize=False)),
                ('testimonial', models.TextField(blank=True, null=True)),
                ('employerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eId', to='account.Employer')),
                ('jobseekerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jbsId', to='account.Jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('ratingId', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('employerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erId', to='account.Employer')),
                ('jobseekerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jbId', to='account.Jobseeker')),
            ],
        ),
    ]
