# Generated by Django 2.2.24 on 2022-06-20 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSeeker',
            fields=[
                ('ServiceId', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=500)),
                ('Jobtype', models.CharField(max_length=500)),
                ('service_photo', models.TextField(null=True)),
                ('Salary', models.IntegerField(null=True)),
                ('City', models.CharField(max_length=500)),
                ('Description', models.TextField(null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='RequestService',
            fields=[
                ('RequestServiceId', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ServiceSeekerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ServiceSeekerId', to='serviceseeker.ServiceSeeker')),
                ('ServiceSeekerUserId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ServiceSeekerUserId', to='account.ServiceSeeker')),
                ('jobseekerServiceId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobseekerServiceId', to='account.Jobseeker')),
            ],
        ),
    ]
