# Generated by Django 2.2.24 on 2022-06-20 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('warningId', models.AutoField(primary_key=True, serialize=False)),
                ('warningMessage', models.CharField(max_length=500)),
                ('warnedUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warnedUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportId', models.AutoField(primary_key=True, serialize=False)),
                ('ReportMessage', models.CharField(max_length=500)),
                ('reported', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
