# Generated by Django 2.2.24 on 2022-06-21 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('NotifyId', models.AutoField(primary_key=True, serialize=False)),
                ('notify', models.CharField(max_length=500)),
                ('notified', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobNot', to='account.Jobseeker')),
                ('notifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empNot', to='account.Employer')),
            ],
        ),
    ]
