# Generated by Django 2.2.24 on 2022-04-30 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('ChatId', models.AutoField(primary_key=True, serialize=False)),
                ('Message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('EmployerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employeId', to='account.Employer')),
                ('JobseekerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobseekerId', to='account.Jobseeker')),
            ],
        ),
    ]
