# Generated by Django 2.2.24 on 2022-06-20 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('ChatId', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('EmployerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employeId', to='account.Employer')),
                ('JobId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jid', to='job.Jobs')),
                ('JobseekerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobseekerId', to='account.Jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('MessageId', models.AutoField(primary_key=True, serialize=False)),
                ('Message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ChatId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatId', to='chat.Chat')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
