# Generated by Django 2.2.24 on 2022-06-20 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vchat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VchatId', models.TextField(blank=True, null=True)),
                ('JobseekerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jsId', to='account.Jobseeker')),
            ],
        ),
    ]
