# Generated by Django 2.2.24 on 2022-04-30 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apply', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('CandidateId', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ApplyId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applyId', to='apply.Apply')),
                ('EmployerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empId', to='account.Employer')),
            ],
        ),
    ]
