# Generated by Django 2.2.24 on 2022-04-25 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('JobId', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=500)),
                ('Deadline', models.CharField(max_length=500)),
                ('Jobtime', models.CharField(max_length=500)),
                ('Jobtype', models.CharField(max_length=500)),
                ('Salary', models.CharField(max_length=500)),
                ('City', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=500)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Employer')),
            ],
        ),
    ]
