# Generated by Django 2.2.24 on 2022-06-20 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('JobId', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=500)),
                ('Deadline', models.DateTimeField()),
                ('Jobtype', models.CharField(max_length=500)),
                ('Salary', models.IntegerField()),
                ('City', models.CharField(max_length=500)),
                ('Description', models.TextField()),
                ('is_freelancer', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Employer')),
            ],
        ),
    ]
